# -*- coding: utf-8 -*-
# emacs: -*- mode: python; py-indent-offset: 4; indent-tabs-mode: nil -*-
# vi: set ft=python sts=4 ts=4 sw=4 et:
"""
Generative augmentation: synthesise images from label maps + bias fields.

- ``gmm_label_to_image`` -- render an intensity image from an integer
  label map by a per-label Gaussian mixture: each voxel takes its label's
  mean plus that label's standard deviation times unit Gaussian noise.
  This is the domain-randomisation synthesis behind contrast-agnostic
  training (synthesise an image from anatomy rather than perturbing a real
  one).
- ``simulate_bias_field`` -- a smooth, low-frequency, multiplicative
  intensity non-uniformity (INU / "bias") field, generated by
  exponentiating an upsampled low-resolution Gaussian field.  This is the
  *forward* (simulation) counterpart to the *corrective* bias-field
  estimators in ``nitrix.bias``.

Both are pure functions of an explicit PRNG key.  ``gmm_label_to_image``
takes explicit per-label statistics so it serves both fixed intensities
and randomised contrast (draw the per-label means / stds in the caller);
``simulate_bias_field`` is a generator parameterised by a magnitude bound.
"""

from __future__ import annotations

from typing import Optional, Sequence

import jax
import jax.numpy as jnp
from jax.typing import DTypeLike
from jaxtyping import Array, Float, Int

from ._common import _coarse_random_field, _default_float

__all__ = ['gmm_label_to_image', 'simulate_bias_field']


def gmm_label_to_image(
    label_map: Int[Array, '*spatial'],
    means: Float[Array, 'n_labels'],
    stds: Float[Array, 'n_labels'],
    key: Array,
    *,
    nonneg: bool = True,
) -> Float[Array, '*spatial']:
    """Render an image from a label map by per-label Gaussian sampling.

    For each voxel, ``image = means[label] + stds[label] * N(0, 1)``,
    a draw from the per-label Gaussian.  Passing per-label statistics
    explicitly (rather than drawing them inside) keeps this a pure render:
    supply fixed ``means`` / ``stds`` for a deterministic intensity map,
    or draw them per call (e.g. ``means ~ U(...)``, ``stds ~ U(...)``) for
    the ever-changing-contrast domain-randomisation augmentation.

    Parameters
    ----------
    label_map
        Integer labels in ``[0, n_labels)``.
    means, stds
        Per-label mean and within-label standard deviation, ``(n_labels,)``.
    key
        PRNG key for the per-voxel unit-Gaussian draw.
    nonneg
        Clamp the output at 0 (default ``True``).

    Returns
    -------
    Intensity image with the shape of ``label_map``.
    """
    idx = label_map.astype(jnp.int32)
    noise = jax.random.normal(key, label_map.shape, dtype=means.dtype)
    image = means[idx] + stds[idx] * noise
    if nonneg:
        image = jnp.maximum(image, 0.0)
    return image


def simulate_bias_field(
    spatial_shape: Sequence[int],
    key: Array,
    *,
    max_std: float = 0.5,
    grid_fraction: float = 0.04,
    dtype: Optional[DTypeLike] = None,
) -> Float[Array, '*spatial']:
    """Simulate a smooth multiplicative intensity non-uniformity field.

    Draws a low-resolution Gaussian field (per-voxel standard deviation
    ``~ U(0, max_std)``) on a coarse grid (``round(shape *
    grid_fraction)`` per axis), linearly upsamples it to
    ``spatial_shape``, and exponentiates.  The result is a smooth,
    strictly-positive field with mean near 1 -- multiply an image by it to
    impose a realistic low-frequency bias.  ``max_std == 0`` gives an
    all-ones (no-op) field.

    Returns
    -------
    Multiplicative field with shape ``spatial_shape``.
    """
    dt = _default_float() if dtype is None else dtype
    k_std, k_field = jax.random.split(key, 2)
    std = jax.random.uniform(k_std, (), dtype=dt, minval=0.0, maxval=max_std)
    full = _coarse_random_field(
        spatial_shape, k_field, std=std, grid_fraction=grid_fraction, dtype=dt
    )
    return jnp.exp(full)
