# -*- coding: utf-8 -*-
"""Pallas Triton vs JAX wall-time for ``semiring_matmul``.

The dense semiring matmul is the kernel where Pallas actually runs
natively on Ampere+ (the ELL kernel falls back to JAX -- see
``bench/G0_ELL_REPORT.md``).  This script is how we tell whether the
Pallas path is worth its complexity: we want a sustained speed-up over
the JAX fallback on the algebras ``jnp.matmul`` can't accelerate
(``LOG``, ``TROPICAL_*``, ``EUCLIDEAN``).  ``REAL`` is included as a
ceiling; users who care about real-semiring throughput should call
``jnp.matmul`` directly.

Per the harness's standing rule, first calls (compile + execute) are
discarded; the reported number is the median wall-time across timed
post-warm-up runs.  See ``bench/_util.py``.

Reproduce::

    python bench/perf_semiring_matmul.py
    python bench/perf_semiring_matmul.py --quick
"""
from __future__ import annotations

import argparse
from pathlib import Path

import jax
import jax.numpy as jnp

from nitrix.semiring import (
    EUCLIDEAN,
    LOG,
    REAL,
    TROPICAL_MAX_PLUS,
    semiring_matmul,
)

from _util import (
    BenchSample,
    bench_call,
    format_us,
    host_summary,
    timed_jit,
)


HERE = Path(__file__).parent
REPORT_PATH = HERE / 'PERF_SEMIRING_MATMUL.md'


SHAPES = [
    # (m, k, n) -- all divisible by 64 for Pallas tile sweet spots.
    (256, 256, 256),
    (512, 512, 512),
    (1024, 1024, 1024),
    (2048, 1024, 2048),
]

QUICK_SHAPES = [(256, 256, 256), (512, 512, 512)]

ALGEBRAS = [REAL, LOG, TROPICAL_MAX_PLUS, EUCLIDEAN]


def make_pair(m: int, k: int, n: int, seed: int):
    key = jax.random.key(seed)
    ka, kb = jax.random.split(key)
    A = jax.random.normal(ka, (m, k), dtype=jnp.float32)
    B = jax.random.normal(kb, (k, n), dtype=jnp.float32)
    # Land on device.
    A = jax.block_until_ready(A)
    B = jax.block_until_ready(B)
    return A, B


def run(shapes, algebras, warmup, repeats):
    rows = []
    for shape in shapes:
        m, k, n = shape
        A, B = make_pair(m, k, n, seed=hash(shape) & 0xFFFF)
        for algebra in algebras:
            row = {
                'm': m, 'k': k, 'n': n,
                'algebra': algebra.name,
            }
            for backend in ('jax', 'pallas-cuda'):
                fn = timed_jit(
                    lambda A_, B_, _a=algebra, _b=backend: semiring_matmul(
                        A_, B_, semiring=_a, backend=_b,
                    )
                )
                try:
                    sample: BenchSample = bench_call(
                        fn, A, B, warmup=warmup, repeats=repeats,
                    )
                    row[f'{backend}_compile_s'] = sample.compile_s
                    row[f'{backend}_warm_s'] = sample.warm_s
                except Exception as e:  # pragma: no cover - bench script
                    row[f'{backend}_warm_s'] = None
                    row[f'{backend}_err'] = repr(e)[:200]

            # Cross-backend speed-up.
            j = row.get('jax_warm_s')
            p = row.get('pallas-cuda_warm_s')
            if j and p:
                row['pallas_speedup_x'] = j / p
            rows.append(row)
    return rows


def render_report(rows, host) -> str:
    lines = [
        '# Perf — `semiring_matmul` Pallas Triton vs JAX',
        '',
        '> Generated by `bench/perf_semiring_matmul.py`.  First-call',
        '> compile time is reported separately from the steady-state',
        '> wall-time (median of timed runs after warm-up).',
        '',
        '## Host',
        '',
        f'- Device: {host["device"]}',
        f'- Platform: {host["platform"]}',
        f'- JAX: {host["jax_version"]}',
        '',
        '## Steady-state wall-time (post-warm-up median)',
        '',
        '| m | k | n | algebra | JAX | Pallas | Pallas speed-up |',
        '|---|---|---|---------|----:|-------:|----------------:|',
    ]
    for r in rows:
        j = r.get('jax_warm_s')
        p = r.get('pallas-cuda_warm_s')
        sp = r.get('pallas_speedup_x')
        lines.append(
            '| {m} | {k} | {n} | {a} | {j} | {p} | {sp} |'.format(
                m=r['m'], k=r['k'], n=r['n'], a=r['algebra'],
                j=format_us(j) if j else 'n/a',
                p=format_us(p) if p else 'n/a',
                sp=f'{sp:.2f}×' if sp else 'n/a',
            )
        )

    lines += [
        '',
        '## First-call cost (compile + execute, *not* a steady-state number)',
        '',
        '| m | k | n | algebra | JAX compile | Pallas compile |',
        '|---|---|---|---------|------------:|---------------:|',
    ]
    for r in rows:
        jc = r.get('jax_compile_s')
        pc = r.get('pallas-cuda_compile_s')
        lines.append(
            '| {m} | {k} | {n} | {a} | {jc} | {pc} |'.format(
                m=r['m'], k=r['k'], n=r['n'], a=r['algebra'],
                jc=format_us(jc) if jc else 'n/a',
                pc=format_us(pc) if pc else 'n/a',
            )
        )

    lines += [
        '',
        '## Interpretation',
        '',
        '- The reported wall-time is the *median* of timed runs after',
        '  ``warmup`` un-timed calls; first-call compile cost is in the',
        '  separate compile-time table.  Compile times above ~5 s on',
        '  cold cache should be reproducible across re-runs in the same',
        '  process (JAX caches the lowered HLO; Pallas caches the',
        '  Triton lowering).',
        '- Speed-up < 1× on a given algebra is a signal the Pallas',
        '  kernel needs tile / unroll re-tuning -- file as an issue',
        '  against the kernel, not as a missing feature.',
        '- For ``REAL``, the more relevant baseline is ``jnp.matmul``',
        '  with default precision (tensor cores).  This bench compares',
        '  against the same-algebra reference (CUDA cores) so the',
        '  numbers are apples-to-apples with the other algebras.',
    ]
    return '\n'.join(lines) + '\n'


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--warmup', type=int, default=3)
    ap.add_argument('--repeats', type=int, default=10)
    ap.add_argument('--quick', action='store_true')
    args = ap.parse_args()
    shapes = QUICK_SHAPES if args.quick else SHAPES
    host = host_summary()
    rows = run(shapes, ALGEBRAS, warmup=args.warmup, repeats=args.repeats)
    report = render_report(rows, host)
    REPORT_PATH.write_text(report)
    print(report)
    print(f'Wrote {REPORT_PATH}.')


if __name__ == '__main__':
    main()
